[package]
name = "warden-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { version = "1.0.0-alpha.7", features = ["pratt"] }
strum = "0.26"
strum_macros = "0.26"
ariadne = { version = "0.4.1", features = ["auto-color"] }